abbr ... "cd ../.."
abbr .... "cd ../../.."
abbr be "bundle exec"
abbr dc "docker-compose"
abbr fopen "vi ~/.config/fish/config.fish"
abbr fource "source ~/.config/fish/config.fish"
abbr github "web-search github"
abbr goog "web-search google"
abbr google "web-search google"
abbr gti "git"
abbr k "kubecolor"
abbr mine "code"
abbr shrug "echo '¯\_(ツ)_/¯' | pbcopy "
abbr so "web-search stackoverflow"
abbr speedtest "networkQuality -v"
