---
name: Lint files
"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Install RuboCop
        run: gem install rubocop

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint Ruby filea
        run: rubocop

      - name: Lint YAML files
        run: yamllint .
